name: PR
run-name: ${{ github.base_ref }} branch verification
on: pull_request
jobs:
  build-and-run-tests:
    name: ${{ matrix.configs.name }} (${{ matrix.build_type }}) Build and Run tests
    runs-on: ${{ matrix.configs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create build folder
        run: |
          mkdir build
          cd build
      - name: Build
        run: |
          cd build
          cmake .. -DCMAKE_C_COMPILER=${{ matrix.configs.CC }} -CMAKE_CXX_COMPILER=${{ matrix.configs.CXX }}
      - name: LS folder
        run: |
          ls

    strategy:
      fail-fast: true
      matrix:
        configs: # Better to add os:macos-latest later
          - {
            name: Ubuntu clang,
            os: ubuntu-latest,
            CC: clang,
            CXX: clang++
          }
          - {
            name: Ubuntu gcc,
            os: ubuntu-latest,
            CC: gcc,
            CXX: g++
          }
          - {
            name: Windows MSVC,
            os: windows-latest,
            CC: gcc,
            CXX: g++
          }
          - {
            name: Windows clang,
            os: windows-latest,
            CC: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/Llvm/bin/clang-cl.exe",
            CXX: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/Llvm/bin/clang-cl.exe"
          }
        build_type: [Debug] # Better to add Release later
