name: PR
run-name: ${{ github.base_ref }} branch verification
on: pull_request
jobs:
  build-and-run-tests:
    name: ${{ matrix.os }}:${{ matrix.config }} Build and Run tests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Test cmake
        run: cmake --version
      - name: Test gcc
        run: gcc --version
      - name: Test clang
        run: clang --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: ON
          config: ${{ matrix.config }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config: [Release, Debug]
