name: PR verification
run-name: PR verification - ${{ github.event.pull_request.title }}
on: pull_request
jobs:
  build-and-run-tests:
    name: ${{ matrix.configs.name }} (${{ matrix.build_type }}) Build and Run tests
    runs-on: ${{ matrix.configs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache cmake dependencies
        id: cmake-deps
        uses: actions/cache@v3
        with:
          path: build/_deps

      - if: ${{ steps.cmake-deps.outputs.cache-hit != 'true' }}
        name: Notify that cmake don't have cash
        continue-on-error: true
        run: echo "Cmake don't have dependencies cache"

      - name: Create build folder
        run: mkdir build

      - name: Configuration
        working-directory: ./build
        run: cmake ${{ matrix.configs.cmake_args }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

      - name: Build
        working-directory: ./build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Run tests
        working-directory: ./build
        run: ctest --output-on-failure

    strategy:
      fail-fast: false
      matrix:
        configs: # Better to add os:macos-latest later
          - {
            name: Ubuntu clang,
            os: ubuntu-latest,
            cmake_args: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++,
          }
          - {
            name: Ubuntu gcc,
            os: ubuntu-latest,
            cmake_args: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++,
          }
          # Uncomment when https://github.com/actions/runner-images/issues/8344 will be solved
          #- {
          #  name: Windows MSVC,
          #  os: windows-latest,
          #}
          #- {
          #  name: Windows clang,
          #  os: windows-latest,
          #  cmake_args: -T ClangCl,
          #}
        build_type: [Release] # Better to add Release later
