name: PR
run-name: ${{ github.base_ref }} branch verification
on: pull_request
jobs:
  build-and-run-tests:
    name: ${{ matrix.configs.name }} (${{ matrix.build_type }}) Build and Run tests
    runs-on: ${{ matrix.configs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create build folder
        run: mkdir build
      - name: Build
        working-directory: ./build
        run: |
          cmake .. ${{ matrix.configs.cmake_args }} ${{ matrix.configs.build_type_argument_name }} ${{ matrix.build_type }}
          cmake --build .
      - name: Run tests
        working-directory: ./build
        run: |
          ctest

    strategy:
      fail-fast: false
      matrix:
        configs: # Better to add os:macos-latest later
          - {
            name: Ubuntu clang,
            os: ubuntu-latest,
            cmake_args: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++,
            build_type_argument_name: -DCMAKE_BUILD_TYPE=,
          }
          - {
            name: Ubuntu gcc,
            os: ubuntu-latest,
            cmake_args: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++,
            build_type_argument_name: -DCMAKE_BUILD_TYPE=,
          }
          - {
            name: Windows MSVC,
            os: windows-latest,
            build_type_argument_name: --config ,
          }
          - {
            name: Windows clang,
            os: windows-latest,
            cmake_args: -T ClangCl,
            build_type_argument_name: --config ,
          }
        build_type: [Release, Debug] # Better to add Release later
