name: PR
run-name: ${{ github.event.pull_request.title }} pull request verification
on: pull_request
jobs:
  build-and-run-tests:
    name: ${{ matrix.configs.name }} (${{ matrix.build_type }}) Build and Run tests
    runs-on: ${{ matrix.configs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create build folder
        run: mkdir build
      - name: Build
        working-directory: ./build
        run: |
          cmake ${{ matrix.configs.cmake_args }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
          cmake --build --config  ${{ matrix.build_type }} .
      - name: Run tests
        working-directory: ./build
        run: |
          ctest

    strategy:
      fail-fast: false
      matrix:
        configs: # Better to add os:macos-latest later
          - {
            name: Ubuntu clang,
            os: ubuntu-latest,
            cmake_args: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++,
          }
          - {
            name: Ubuntu gcc,
            os: ubuntu-latest,
            cmake_args: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++,
          }
          - {
            name: Windows MSVC,
            os: windows-latest,
          }
          - {
            name: Windows clang,
            os: windows-latest,
            cmake_args: -T ClangCl,
          }
        build_type: [Release, Debug] # Better to add Release later
